# Generated by Django 5.2.7 on 2025-10-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key_value', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
    ]
